### PR TITLE
Newsweek Web Page Clone working-branch pull request

### PR DESCRIPTION
**Pull request by Albertino2020**
This is an individual project from the Microverse Main Curriculum. I built a replica of the news site Newsweek.com using the Bootstrap framework. Almost all major features were cloned and Bootstrap was used everywhere in the project, except in what concerns minor adjustments such as adding padding and margin, for which I created local ad hoc classes for the effect. To meet the goal of responsiveness for all screen sizes, I also used media queries and some other HTML and CSS tools.

### CODE REVIEW

**Review by MarioDena — CHANGES_REQUESTED** [review]
Hello, good work on your project it looks good 🏅 , however your repository has unused/unrelated files.

## Changes Required 

- [ ] Please clean your repository, there are unused empty files with weird names along with even a .deb package file, also when working with node modules they should be added to .gitignore

- [ ] There are repeated rules on your CSS please remember to use good coding practices. For example: `color: black !important;` is used 6 times. Here is an article you can find useful: https://speckyboy.com/good-bad-css-practices/

- [ ] Please avoid using `!important;` this project is simple enough to be able to avoid using it. If you find yourself needing it its probably because there is a design flaw on your code. article above can explain you why.

- [ ] The body of the page must __NOT__ grow bigger than 1300px. If you need to test for a resolution higher than your native one use the developer tools. For future projects I recommend you to test all the way up to 1800p resolution.

- [ ] You are missing parts of the layout. Please implement them.

img

After making the requested changes please resubmit your project for review.

Cheers!!

**Comment by Albertino2020** [comment]
Thanks a lot for your review. I completed all tasks required and consistently tested the web page on different screen sizes, from the smallest to the largest. The page is behaving according to expectations. Regarding repetitions in the CSS file, as you can see, they are necessary because I am dealing with properties that are rewriting the original Bootstrap properties, and because I linked the page directly to the Bootstrap CSS source, rewriting properties are not easily taking unless I use "!important.". There is no way I can create one class for the color or a few properties that I am using, because the same Bootstrap classes are being used in different parts of the page, with different values for colors, namely, blue, red, white, black and grey, and paddings of margins, which are repeated but are not common. So the changes are being done locally. If I create different classes for each of these properties, of for a few of them, I definitively will create more classes than necessary and will make more repetitions indeed, because I will have to repeat them, because it seems not possible to make them universal.
 appreciate your understanding on this matter.

**Comment by christianotieno** [comment]
## Pull Request under review by Christian Otieno (TSE)

**Review by christianotieno — CHANGES_REQUESTED** [review]
## Awesome work @Albertino2020 

### [The clone](https://rawcdn.githack.com/Albertino2020/newsweek.com-clone/56a9a7ba2bad11560fceab7b3ca9ab66113d67b4/index.html) shows good use of Bootstrap classes and its very responsive. :100: 

A few required changes: Note that for this project, we have to make sure nothing is messed up. Please see the difference in the source page and the clone below: 

| [Current clone](https://rawcdn.githack.com/Albertino2020/newsweek.com-clone/56a9a7ba2bad11560fceab7b3ca9ab66113d67b4/index.html) | [Source Page](https://www.newsweek.com/) |
|:-----:|:-----:|
| clone | newsweek|

- The contents are spanning the entire screen width (not really centred as they should). We can wrap all of them in the `container` class as one way to solve this issue.
- Everything else is okay and good job implementing the previously required changes and your detailed explanation is well received.


#### :recycle:  Submit another code review request once you are through with this. :+1: 

#### Feel free to reach me on slack if you having issues implementing these features. :+1: 

Good luck with your next submission. :star2: 

Cheers
[Christian Otieno](https://github.com/christianotieno)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

**Comment by Albertino2020** [comment]
[cid:ef6e43c8-c466-47cb-8fb6-21d9158ef955]
________________________________
De: Christian Otieno <notifications@github.com>
Enviado: 19 de abril de 2020 01:14
Para: Albertino2020/newsweek.com-clone <newsweek.com-clone@noreply.github.com>
Cc: Albertino Francisco <albertino@ua.pt>; Mention <mention@noreply.github.com>
Assunto: Re: [Albertino2020/newsweek.com-clone] Newsweek Web Page Clone working-branch pull request (#2)


@christianotieno requested changes on this pull request.

Awesome work @Albertino2020<https://github.com/Albertino2020>
The clone<https://rawcdn.githack.com/Albertino2020/newsweek.com-clone/56a9a7ba2bad11560fceab7b3ca9ab66113d67b4/index.html> shows good use of Bootsrap classes and its very responsive. 💯

A few required changes: Note that for this project, we have to make sure nothing is messed up. Please see the difference in the source page and the clone below:

Current clone<https://rawcdn.githack.com/Albertino2020/newsweek.com-clone/56a9a7ba2bad11560fceab7b3ca9ab66113d67b4/index.html>  Source Page<https://www.newsweek.com/>
[clone]<https://user-images.githubusercontent.com/22345961/79676877-5a492300-81f3-11ea-9acb-32acdac3d5d7.png>   [newsweek] <https://user-images.githubusercontent.com/22345961/79676881-659c4e80-81f3-11ea-8768-c7976091a162.png>

  *   The contents are spanning the entire screen width (not really centred as they should). We can wrap all of them in the container class as one way to solve this issue.
  *   Everything else is okay and good job implementing the previously required changes and your detailed explanation is well received.

♻️ Submit another code review request once you are through with this. 👍
Feel free to reach me on slack if you having issues implementing these features. 👍

Good luck with your next submission. 🌟

Cheers
Christian Otieno<https://github.com/christianotieno>

PS: Note that comments tagged as OPTIONAL are not part of the minimum requirements to approve this PR

**Review by christianotieno — APPROVED** [review]
# PROJECT APPROVED :champagne:
##
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on the splendid job @Albertino2020! :+1:
- Be sure to update the README live link to your site. After which you can now merge to master and I wish you all the very best in your next tasks. 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Comment by Albertino2020** [comment]
Thanks once again, Christian. Have a nice day :+1:

**Pull request merged**
